### ISSUE TITLE
handle auth when token expired

### ISSUE THREAD

**Issue by undisplay** [dokla/moncash_python#1]
it will be great if you handle re-auth when the api respond with a 401 token expired

**Comment by Chamane** [comment]
Ah yes! In the next 1.1.0 version we gonna handle this, this way. When we have a 401 error we gonna refresh the token. We gonna have two type of 401 errors:
1) When the token expired (This have been handled directly in the code by controlling the time ourselves.... this have to change to your way)
2) When the credentials (client_id, client_secret) are wrong 

It works as it goes right now but if we handle the token when Moncash tell us that it is expired the API will be faster I think. The glory of REST :)
